# Generated by Django 3.2.13 on 2024-09-25 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('schemes', '0001_initial'), ('schemes', '0002_auto_20240909_1726'), ('schemes', '0003_schemechangelog_schemeteammember')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('schemename', models.CharField(max_length=255)),
                ('ministry', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('moneygranted', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneyspent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=50)),
                ('progress', models.FloatField()),
                ('leadperson', models.CharField(max_length=255)),
                ('lasteditedby', models.CharField(max_length=255)),
                ('timeOfschemeAdded', models.TimeField()),
                ('date', models.DateField()),
                ('srno', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.EmailField(max_length=254)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='schemes.scheme')),
            ],
        ),
    ]
