# Generated by Django 3.2.13 on 2024-09-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluka_name', models.CharField(max_length=100, verbose_name='Taluka Name')),
                ('no_of_schools', models.IntegerField(verbose_name='Number of Schools')),
                ('no_of_hospitals', models.IntegerField(verbose_name='Number of Hospitals')),
                ('no_of_colleges', models.IntegerField(verbose_name='Number of Colleges')),
                ('no_of_universities', models.IntegerField(verbose_name='Number of Universities')),
                ('no_of_railway_stations', models.IntegerField(verbose_name='Number of Railway Stations')),
                ('no_of_bus_stations', models.IntegerField(verbose_name='Number of Bus Stations')),
                ('no_of_post_offices', models.IntegerField(verbose_name='Number of Post Offices')),
                ('no_of_police_stations', models.IntegerField(verbose_name='Number of Police Stations')),
                ('no_of_fire_stations', models.IntegerField(verbose_name='Number of Fire Stations')),
                ('date', models.DateField(auto_now_add=True)),
                ('srno', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalukaPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taluka_name', models.CharField(max_length=100, unique=True)),
                ('total_population', models.IntegerField()),
            ],
        ),
    ]
