# Generated by Django 3.2.13 on 2024-09-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemename', models.CharField(max_length=255)),
                ('ministry', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('moneygranted', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneyspent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(max_length=50)),
                ('progress', models.FloatField()),
                ('leadperson', models.CharField(max_length=255)),
                ('lasteditedby', models.CharField(max_length=255)),
                ('timeOfschemeAdded', models.TimeField()),
                ('date', models.DateField()),
                ('srno', models.IntegerField()),
            ],
        ),
    ]
