# Generated by Django 3.2.13 on 2024-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='id',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='srno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
