# Generated by Django 3.2.13 on 2024-09-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_auto_20240909_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.EmailField(max_length=254)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='schemes.scheme')),
            ],
        ),
    ]
